---
functional:
- Пользователь должен иметь возможность регистрации и авторизации на сайте.
- Пользователь должен иметь возможность пользоваться сайтом без регистрации и авторизации. 
- Пользователь должен иметь возможность создать игру.
- Пользователь должен иметь возможность подлкючиться к уже созданной игре другим человеком.
- Пользователь должен иметь возможность просматривать свой и общий рейтинг, историю игр и статистику.
- Пользователь должен иметь возможность выбирать разные режимы игры, сложность и язык программирования.
- Пользователь должен иметь возможность писать в общий чат и чат лобби, а также отправлять личные сообщения другим пользователям.
- Пользователь должен иметь возможность смены языка программирования во время игры.
- Пользователь должен иметь возможность видеть код другого игрока.
- Пользователь должен иметь возможность настроить свой профиль - выбрать разные языки программирования и сменить отображаемое имя.
- Пользователь должен иметь возможность просматривать свои завершенные игры.
- Пользователь должен иметь возможность создавать игру с ботом.
- Пользователь должен иметь возможность просматривать профили других игроков.
- Пользователь должен иметь возможность регистрации и авторизации через созданные аккаунты на сторонних сервисах.
- Пользователь должен иметь возмжоность выбрать тематику игры.
- Пользователь должне иметь возможность настроить громкость звука и мелодию оповещения.
- Пользователь должен иметь возможность наблюдать за активной игрой других пользователей.
non-functional:
- Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
- Сайт должен быть безопасным и защищать данные пользователя
- Сайт должен быть удобным на мобильном устройстве
- Сайт должен быть протестирован на совместимость с последними версиями браузеров
- Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
- Пользователь должен иметь возможность сменить язык интерфейса сайта.
- Пользователь должен иметь возможность иметь возможность приобрести премиум подписку во всплывающем окне "Restricted content".
- Пользователь должен иметь возможность увидеть статус другого человека в его профиле или нажатии на его никнейм (например, "в игре", "в лобби", "онлайн", "оффлайн").
